baseURL = "https://chiyuu-official.web.app/"
languageCode = "ja-jp"
title = "CHIYUU Official"
theme = "hugo-universal-theme"
themesDir = "../.."
defaultContentLanguage = "ja"
style = "default"
googleAnalytics = "UA-86186566-18"

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 2

[params]
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    customCSS = ["/css/custom.css"]

    defaultKeywords = ["宮城県", "仙台市", "システム開発", "受託", "アプリ"]
    defaultDescription = "宮城県仙台市でITソリューションを提供している智勇(CHIYUU)のHPです。"

    copyright = "Copyright (c) 2017 - 2023, CHIYUU; all rights reserved."

    about_us = "<p>本サイトは屋号が智勇(CHIYUU)の事業主のオフィシャルホームページとなります。</p>"

[params.clients]
    enable = true
    title = "Clients"

[params.features]
    enable = true

[params.carousel]
    enable = true

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "実績紹介"
    subtitle = "現在作成中です。近日公開予定。"

[params.testimonials]
    enable = true
    title = "お客様の声"

[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">info@chiyuu-official.com にて連絡お受けしております。</p>
      <p class="hidden-md hidden-lg">
        <a href="mailto:info@chiyuu-official.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/CHIYUU-Official"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/rikoroku"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:info@chiyuu-official.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
