baseURL = "https://chiyuu-official.com/"
languageCode = "ja-jp"
title = "Official site of CHIYUU"
theme = "hugo-universal-theme"
themesDir = "../.."
defaultContentLanguage = "ja"
style = "default"
googleAnalytics = "G-DKSSVMSQ9V"

[menu]

# Main menu

[[menu.main]]
    identifier="top"
    name = "Top"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "about_me"
    name = "開発者について"
    url  = "https://rikoroku.github.io/"
    weight = 2

[[menu.main]]
    identifier = "contact"
    name = "お問い合わせ"
    url  = "/contact/"
    weight = 3

[params]
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    customCSS = ["/css/custom.css"]

    defaultKeywords = ["宮城県", "仙台市", "システム開発", "受託", "アプリ"]
    defaultDescription = "宮城県仙台市でITソリューションを提供している智勇(CHIYUU)のHPです。"

    copyright = "Copyright (c) 2017 - 2023, CHIYUU; all rights reserved."

    about_us = "<p>本サイトは屋号が智勇(CHIYUU)の事業主のオフィシャルホームページとなります。</p>"

[params.clients]
    enable = true
    title = "Clients"

[params.features]
    enable = true

[params.carousel]
    enable = true

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "開発者紹介"
    subtitle = "2017年1月に開業して以来、多種多様な実績があります。"
    link_url = "https://rikoroku.github.io/"
    link_text = "詳しくはこちらより確認ください。"
    link_blank = true

[params.testimonials]
    enable = true
    title = "お客様の声"

[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"><a href="/contact">お問い合わせ</a>にて連絡お受けしております。</p>
      <p class="hidden-md hidden-lg">
        <a href="/contact" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/CHIYUU-Official"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/rikoroku"
    pre = "<i class='fab fa-2x fa-twitter'></i>"
