baseURL = "https://chiyuu-official.web.app/"
languageCode = "ja-jp"
title = "CHIYUU Official"
theme = "hugo-universal-theme"
themesDir = "../.."
defaultContentLanguage = "ja"
style = "default"
googleAnalytics = "UA-86186566-18"

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url  = "/faq/"
    weight = 2

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 3

[params]
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    customCSS = ["/css/custom.css"]

    defaultKeywords = ["弘前市", "システム開発", "WordPress"]
    defaultDescription = "青森県弘前市でWebシステム開発に関するソリューションを提供している智勇(CHIYUU)のHPです。"

    copyright = "Copyright (c) 2017 - 2020, CHIYUU; all rights reserved."

    about_us = "<p>本サイトは屋号が智勇(CHIYUU)の事業主のオフィシャルホームページとなります。</p>"

[params.clients]
    enable = true
    title = "Clients"

[params.features]
    enable = true

[params.carousel]
    enable = true

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "実績紹介"
    subtitle = "現在作成中です。近日公開予定。"

[params.testimonials]
    enable = true
    title = "お客様の声"

